/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app/route'
import { Route as AppMoviesImport } from './routes/_app/movies'
import { Route as AppContactImport } from './routes/_app/contact'
import { Route as AppAboutImport } from './routes/_app/about'
import { Route as AppIsAuthenticatedRouteImport } from './routes/_app/_isAuthenticated/route'
import { Route as AppIndexRouteImport } from './routes/_app/index/route'
import { Route as AppWatchIdImport } from './routes/_app/watch/$id'
import { Route as AppIsAuthenticatedWatchlistImport } from './routes/_app/_isAuthenticated/watchlist'
import { Route as AppIsAuthenticatedSettingsImport } from './routes/_app/_isAuthenticated/settings'
import { Route as AppIsAuthenticatedProfileImport } from './routes/_app/_isAuthenticated/profile'
import { Route as AppIsAuthenticatedHistoryImport } from './routes/_app/_isAuthenticated/history'
import { Route as AppIsAuthenticatedIsAdminAddImport } from './routes/_app/_isAuthenticated/_isAdmin/add'

// Create/Update Routes

const AppRouteRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppMoviesRoute = AppMoviesImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppContactRoute = AppContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppAboutRoute = AppAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppIsAuthenticatedRouteRoute = AppIsAuthenticatedRouteImport.update({
  id: '/_isAuthenticated',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppIndexRouteRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppWatchIdRoute = AppWatchIdImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

const AppIsAuthenticatedWatchlistRoute =
  AppIsAuthenticatedWatchlistImport.update({
    id: '/watchlist',
    path: '/watchlist',
    getParentRoute: () => AppIsAuthenticatedRouteRoute,
  } as any)

const AppIsAuthenticatedSettingsRoute = AppIsAuthenticatedSettingsImport.update(
  {
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppIsAuthenticatedRouteRoute,
  } as any,
)

const AppIsAuthenticatedProfileRoute = AppIsAuthenticatedProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppIsAuthenticatedRouteRoute,
} as any)

const AppIsAuthenticatedHistoryRoute = AppIsAuthenticatedHistoryImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppIsAuthenticatedRouteRoute,
} as any)

const AppIsAuthenticatedIsAdminAddRoute =
  AppIsAuthenticatedIsAdminAddImport.update({
    id: '/_isAdmin/add',
    path: '/add',
    getParentRoute: () => AppIsAuthenticatedRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/_isAuthenticated': {
      id: '/_app/_isAuthenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppIsAuthenticatedRouteImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/movies': {
      id: '/_app/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof AppMoviesImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/_isAuthenticated/history': {
      id: '/_app/_isAuthenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppIsAuthenticatedHistoryImport
      parentRoute: typeof AppIsAuthenticatedRouteImport
    }
    '/_app/_isAuthenticated/profile': {
      id: '/_app/_isAuthenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppIsAuthenticatedProfileImport
      parentRoute: typeof AppIsAuthenticatedRouteImport
    }
    '/_app/_isAuthenticated/settings': {
      id: '/_app/_isAuthenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppIsAuthenticatedSettingsImport
      parentRoute: typeof AppIsAuthenticatedRouteImport
    }
    '/_app/_isAuthenticated/watchlist': {
      id: '/_app/_isAuthenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AppIsAuthenticatedWatchlistImport
      parentRoute: typeof AppIsAuthenticatedRouteImport
    }
    '/_app/watch/$id': {
      id: '/_app/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof AppWatchIdImport
      parentRoute: typeof AppRouteImport
    }
    '/_app/_isAuthenticated/_isAdmin/add': {
      id: '/_app/_isAuthenticated/_isAdmin/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AppIsAuthenticatedIsAdminAddImport
      parentRoute: typeof AppIsAuthenticatedRouteImport
    }
  }
}

// Create and export the route tree

interface AppIsAuthenticatedRouteRouteChildren {
  AppIsAuthenticatedHistoryRoute: typeof AppIsAuthenticatedHistoryRoute
  AppIsAuthenticatedProfileRoute: typeof AppIsAuthenticatedProfileRoute
  AppIsAuthenticatedSettingsRoute: typeof AppIsAuthenticatedSettingsRoute
  AppIsAuthenticatedWatchlistRoute: typeof AppIsAuthenticatedWatchlistRoute
  AppIsAuthenticatedIsAdminAddRoute: typeof AppIsAuthenticatedIsAdminAddRoute
}

const AppIsAuthenticatedRouteRouteChildren: AppIsAuthenticatedRouteRouteChildren =
  {
    AppIsAuthenticatedHistoryRoute: AppIsAuthenticatedHistoryRoute,
    AppIsAuthenticatedProfileRoute: AppIsAuthenticatedProfileRoute,
    AppIsAuthenticatedSettingsRoute: AppIsAuthenticatedSettingsRoute,
    AppIsAuthenticatedWatchlistRoute: AppIsAuthenticatedWatchlistRoute,
    AppIsAuthenticatedIsAdminAddRoute: AppIsAuthenticatedIsAdminAddRoute,
  }

const AppIsAuthenticatedRouteRouteWithChildren =
  AppIsAuthenticatedRouteRoute._addFileChildren(
    AppIsAuthenticatedRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppIndexRouteRoute: typeof AppIndexRouteRoute
  AppIsAuthenticatedRouteRoute: typeof AppIsAuthenticatedRouteRouteWithChildren
  AppAboutRoute: typeof AppAboutRoute
  AppContactRoute: typeof AppContactRoute
  AppMoviesRoute: typeof AppMoviesRoute
  AppWatchIdRoute: typeof AppWatchIdRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRouteRoute: AppIndexRouteRoute,
  AppIsAuthenticatedRouteRoute: AppIsAuthenticatedRouteRouteWithChildren,
  AppAboutRoute: AppAboutRoute,
  AppContactRoute: AppContactRoute,
  AppMoviesRoute: AppMoviesRoute,
  AppWatchIdRoute: AppWatchIdRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof AppIsAuthenticatedRouteRouteWithChildren
  '/': typeof AppIndexRouteRoute
  '/about': typeof AppAboutRoute
  '/contact': typeof AppContactRoute
  '/movies': typeof AppMoviesRoute
  '/history': typeof AppIsAuthenticatedHistoryRoute
  '/profile': typeof AppIsAuthenticatedProfileRoute
  '/settings': typeof AppIsAuthenticatedSettingsRoute
  '/watchlist': typeof AppIsAuthenticatedWatchlistRoute
  '/watch/$id': typeof AppWatchIdRoute
  '/add': typeof AppIsAuthenticatedIsAdminAddRoute
}

export interface FileRoutesByTo {
  '/': typeof AppIndexRouteRoute
  '': typeof AppIsAuthenticatedRouteRouteWithChildren
  '/about': typeof AppAboutRoute
  '/contact': typeof AppContactRoute
  '/movies': typeof AppMoviesRoute
  '/history': typeof AppIsAuthenticatedHistoryRoute
  '/profile': typeof AppIsAuthenticatedProfileRoute
  '/settings': typeof AppIsAuthenticatedSettingsRoute
  '/watchlist': typeof AppIsAuthenticatedWatchlistRoute
  '/watch/$id': typeof AppWatchIdRoute
  '/add': typeof AppIsAuthenticatedIsAdminAddRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/': typeof AppIndexRouteRoute
  '/_app/_isAuthenticated': typeof AppIsAuthenticatedRouteRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/movies': typeof AppMoviesRoute
  '/_app/_isAuthenticated/history': typeof AppIsAuthenticatedHistoryRoute
  '/_app/_isAuthenticated/profile': typeof AppIsAuthenticatedProfileRoute
  '/_app/_isAuthenticated/settings': typeof AppIsAuthenticatedSettingsRoute
  '/_app/_isAuthenticated/watchlist': typeof AppIsAuthenticatedWatchlistRoute
  '/_app/watch/$id': typeof AppWatchIdRoute
  '/_app/_isAuthenticated/_isAdmin/add': typeof AppIsAuthenticatedIsAdminAddRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/'
    | '/about'
    | '/contact'
    | '/movies'
    | '/history'
    | '/profile'
    | '/settings'
    | '/watchlist'
    | '/watch/$id'
    | '/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/contact'
    | '/movies'
    | '/history'
    | '/profile'
    | '/settings'
    | '/watchlist'
    | '/watch/$id'
    | '/add'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/_isAuthenticated'
    | '/_app/about'
    | '/_app/contact'
    | '/_app/movies'
    | '/_app/_isAuthenticated/history'
    | '/_app/_isAuthenticated/profile'
    | '/_app/_isAuthenticated/settings'
    | '/_app/_isAuthenticated/watchlist'
    | '/_app/watch/$id'
    | '/_app/_isAuthenticated/_isAdmin/add'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app"
      ]
    },
    "/_app": {
      "filePath": "_app/route.tsx",
      "children": [
        "/_app/",
        "/_app/_isAuthenticated",
        "/_app/about",
        "/_app/contact",
        "/_app/movies",
        "/_app/watch/$id"
      ]
    },
    "/_app/": {
      "filePath": "_app/index/route.tsx",
      "parent": "/_app"
    },
    "/_app/_isAuthenticated": {
      "filePath": "_app/_isAuthenticated/route.tsx",
      "parent": "/_app",
      "children": [
        "/_app/_isAuthenticated/history",
        "/_app/_isAuthenticated/profile",
        "/_app/_isAuthenticated/settings",
        "/_app/_isAuthenticated/watchlist",
        "/_app/_isAuthenticated/_isAdmin/add"
      ]
    },
    "/_app/about": {
      "filePath": "_app/about.tsx",
      "parent": "/_app"
    },
    "/_app/contact": {
      "filePath": "_app/contact.tsx",
      "parent": "/_app"
    },
    "/_app/movies": {
      "filePath": "_app/movies.tsx",
      "parent": "/_app"
    },
    "/_app/_isAuthenticated/history": {
      "filePath": "_app/_isAuthenticated/history.tsx",
      "parent": "/_app/_isAuthenticated"
    },
    "/_app/_isAuthenticated/profile": {
      "filePath": "_app/_isAuthenticated/profile.tsx",
      "parent": "/_app/_isAuthenticated"
    },
    "/_app/_isAuthenticated/settings": {
      "filePath": "_app/_isAuthenticated/settings.tsx",
      "parent": "/_app/_isAuthenticated"
    },
    "/_app/_isAuthenticated/watchlist": {
      "filePath": "_app/_isAuthenticated/watchlist.tsx",
      "parent": "/_app/_isAuthenticated"
    },
    "/_app/watch/$id": {
      "filePath": "_app/watch/$id.tsx",
      "parent": "/_app"
    },
    "/_app/_isAuthenticated/_isAdmin/add": {
      "filePath": "_app/_isAuthenticated/_isAdmin/add.tsx",
      "parent": "/_app/_isAuthenticated"
    }
  }
}
ROUTE_MANIFEST_END */
